### ISSUE TITLE
Need assignment for Jan 25 pushed to your repository! 

### ISSUE THREAD

**Issue by natenolting** [nienaber9/Assignments_January_16#2]
@nienaber9   you need to follow the instructions for assignment from Jan 25 https://github.com/natenolting/BUAD-3283-E-Commerce-Web-Development/blob/spring2018/course_assignment/course_assignment_06_January_25.md and push those changes to your repository so I can grade it.

**Comment by nienaber9** [comment]
I actually dropped the class last week, so I will be no longer attending

**Comment by natenolting** [comment]
Oh ok, I guess I never got notified. Sorry to see you go. If I may ask, what was the reason?

**Comment by nienaber9** [comment]
I’ve never coded before and I was looking for a more entry level class to learn the basics. I’m going to take the book from the class and use codecademy and Mimo to learn at a slower pace

**Comment by natenolting** [comment]
I’m trying to make it kinda basic, but there’s hurdles we need to get over before we can get to the “E-Commerce” part of the class. Keep up with my notes for the class if you want https://github.com/natenolting/BUAD-3283-E-Commerce-Web-Development/tree/spring2018/course_notes <https://github.com/natenolting/BUAD-3283-E-Commerce-Web-Development/tree/spring2018/course_notes>  Thanks for trying and good luck!

-Nate
